name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: |
          curl -fsS --max-time 10 "https://graph-query.onrender.com/health"

